package sets

type SetName []string

var (
	// Standard metal
	BronzeLg             = SetName([]string{"Bronze full helm", "Bronze platebody", "Bronze platelegs", "Bronze kiteshield"})
	IronLg               = SetName([]string{"Iron full helm", "Iron platebody", "Iron platelegs", "Iron kiteshield"})
	SteelLg              = SetName([]string{"Steel full helm", "Steel platebody", "Steel platelegs", "Steel kiteshield"})
	BlackLg              = SetName([]string{"Black full helm", "Black platebody", "Black platelegs", "Black kiteshield"})
	MithrilLg            = SetName([]string{"Mithril full helm", "Mithril platebody", "Mithril platelegs", "Mithril kiteshield"})
	AdamantLg            = SetName([]string{"Adamant full helm", "Adamant platebody", "Adamant platelegs", "Adamant kiteshield"})
	RuneLg               = SetName([]string{"Rune full helm", "Rune platebody", "Rune platelegs", "Rune kiteshield"})
	DragonLg             = SetName([]string{"Dragon full helm", "Dragon platebody", "Dragon platelegs", "Dragon kiteshield"})
	BronzeGoldTrimmedLg  = SetName([]string{"Bronze full helm (g)", "Bronze platebody (g)", "Bronze platelegs (g)", "Bronze kiteshield (g)"})
	IronGoldTrimmedLg    = SetName([]string{"Iron full helm (g)", "Iron platebody (g)", "Iron platelegs (g)", "Iron kiteshield (g)"})
	SteelGoldTrimmedLg   = SetName([]string{"Steel full helm (g)", "Steel platebody (g)", "Steel platelegs (g)", "Steel kiteshield (g)"})
	BlackGoldTrimmedLg   = SetName([]string{"Black full helm (g)", "Black platebody (g)", "Black platelegs (g)", "Black kiteshield (g)"})
	MithrilGoldTrimmedLg = SetName([]string{"Mithril full helm (g)", "Mithril platebody (g)", "Mithril platelegs (g)", "Mithril kiteshield (g)"})
	AdamantGoldTrimmedLg = SetName([]string{"Adamant full helm (g)", "Adamant platebody (g)", "Adamant platelegs (g)", "Adamant kiteshield (g)"})
	RuneGoldTrimmedLg    = SetName([]string{"Rune full helm (g)", "Rune platebody (g)", "Rune platelegs (g)", "Rune kiteshield (g)"})
	GildedLg             = SetName([]string{"Gilded full helm", "Gilded platebody", "Gilded platelegs", "Gilded kiteshield"})
	BronzeTrimmedLg      = SetName([]string{"Bronze full helm (t)", "Bronze platebody (t)", "Bronze platelegs (t)", "Bronze kiteshield (t)"})
	IronTrimmedLg        = SetName([]string{"Iron full helm (t)", "Iron platebody (t)", "Iron platelegs (t)", "Iron kiteshield (t)"})
	BlackTrimmedLg       = SetName([]string{"Black full helm (t)", "Black platebody (t)", "Black platelegs (t)", "Black kiteshield (t)"})
	MithrilTrimmedLg     = SetName([]string{"Mithril full helm (t)", "Mithril platebody (t)", "Mithril platelegs (t)", "Mithril kiteshield (t)"})
	AdamantTrimmedLg     = SetName([]string{"Adamant full helm (t)", "Adamant platebody (t)", "Adamant platelegs (t)", "Adamant kiteshield (t)"})
	RuneTrimmedLg        = SetName([]string{"Rune full helm (t)", "Rune platebody (t)", "Rune platelegs (t)", "Rune kiteshield (t)"})
	GuthixLg             = SetName([]string{"Guthix full helm", "Guthix platebody", "Guthix platelegs", "Guthix kiteshield"})
	SaradominLg          = SetName([]string{"Saradomin full helm", "Saradomin platebody", "Saradomin platelegs", "Saradomin kiteshield"})
	ZamorakLg            = SetName([]string{"Zamorak full helm", "Zamorak platebody", "Zamorak platelegs", "Zamorak kiteshield"})
	AncientLg            = SetName([]string{"Ancient full helm", "Ancient platebody", "Ancient platelegs", "Ancient kiteshield"})
	ArmadylLg            = SetName([]string{"Armadyl full helm", "Armadyl platebody", "Armadyl platelegs", "Armadyl kiteshield"})
	BandosLg             = SetName([]string{"BandosLg full helm", "BandosLg platebody", "BandosLg platelegs", "BandosLg kiteshield"})
	BronzeSk             = SetName([]string{"Bronze full helm", "Bronze platebody", "Bronze plateskirt", "Bronze kiteshield"})
	IronSk               = SetName([]string{"Iron full helm", "Iron platebody", "Iron plateskirt", "Iron kiteshield"})
	SteelSk              = SetName([]string{"Steel full helm", "Steel platebody", "Steel plateskirt", "Steel kiteshield"})
	BlacksSk             = SetName([]string{"Black full helm", "Black platebody", "Black plateskirt", "Black kiteshield"})
	MithriSk             = SetName([]string{"Mithril full helm", "Mithril platebody", "Mithril plateskirt", "Mithril kiteshield"})
	AdamantSk            = SetName([]string{"Adamant full helm", "Adamant platebody", "Adamant plateskirt", "Adamant kiteshield"})
	RuneSk               = SetName([]string{"Rune full helm", "Rune platebody", "Rune plateskirt", "Rune kiteshield"})
	DragonSk             = SetName([]string{"Dragon full helm", "Dragon platebody", "Dragon plateskirt", "Dragon kiteshield"})
	BronzeGoldTrimmedSk  = SetName([]string{"Bronze full helm (g)", "Bronze platebody (g)", "Bronze plateskirt (g)", "Bronze kiteshield (g)"})
	IronGoldTrimmedSk    = SetName([]string{"Iron full helm (g)", "Iron platebody (g)", "Iron plateskirt (g)", "Iron kiteshield (g)"})
	SteelGoldTrimmedSk   = SetName([]string{"Steel full helm (g)", "Steel platebody (g)", "Steel plateskirt (g)", "Steel kiteshield (g)"})
	BlackGoldTrimmedSk   = SetName([]string{"Black full helm (g)", "Black platebody (g)", "Black plateskirt (g)", "Black kiteshield (g)"})
	MithrilGoldTrimmedSk = SetName([]string{"Mithril full helm (g)", "Mithril platebody (g)", "Mithril plateskirt (g)", "Mithril kiteshield (g)"})
	AdamantGoldTrimmedSk = SetName([]string{"Adamant full helm (g)", "Adamant platebody (g)", "Adamant plateskirt (g)", "Adamant kiteshield (g)"})
	RuneGoldTrimmedSk    = SetName([]string{"Rune full helm (g)", "Rune platebody (g)", "Rune plateskirt (g)", "Rune kiteshield (g)"})
	GildedSk             = SetName([]string{"Gilded full helm", "Gilded platebody", "Gilded plateskirt", "Gilded kiteshield"})
	BronzeTrimmedSk      = SetName([]string{"Bronze full helm (t)", "Bronze platebody (t)", "Bronze plateskirt (t)", "Bronze kiteshield (t)"})
	IronTrimmedSk        = SetName([]string{"Iron full helm (t)", "Iron platebody (t)", "Iron plateskirt (t)", "Iron kiteshield (t)"})
	BlackTrimmedSk       = SetName([]string{"Black full helm (t)", "Black platebody (t)", "Black plateskirt (t)", "Black kiteshield (t)"})
	MithrilTrimmedSk     = SetName([]string{"Mithril full helm (t)", "Mithril platebody (t)", "Mithril plateskirt (t)", "Mithril kiteshield (t)"})
	AdamantTrimmedSk     = SetName([]string{"Adamant full helm (t)", "Adamant platebody (t)", "Adamant plateskirt (t)", "Adamant kiteshield (t)"})
	RuneTrimmedSk        = SetName([]string{"Rune full helm (t)", "Rune platebody (t)", "Rune plateskirt (t)", "Rune kiteshield (t)"})
	GuthixSk             = SetName([]string{"Guthix full helm", "Guthix platebody", "Guthix plateskirt", "Guthix kiteshield"})
	SaradominSk          = SetName([]string{"Saradomin full helm", "Saradomin platebody", "Saradomin plateskirt", "Saradomin kiteshield"})
	ZamorakSk            = SetName([]string{"Zamorak full helm", "Zamorak platebody", "Zamorak plateskirt", "Zamorak kiteshield"})
	AncientSk            = SetName([]string{"Ancient full helm", "Ancient platebody", "Ancient plateskirt", "Ancient kiteshield"})
	ArmadylSk            = SetName([]string{"Armadyl full helm", "Armadyl platebody", "Armadyl plateskirt", "Armadyl kiteshield"})
	BandosSk             = SetName([]string{"BandosLg full helm", "BandosLg platebody", "BandosLg plateskirt", "BandosLg kiteshield"})
	Initiate             = SetName([]string{"Initiate sallet", "Initiate hauberk", "Initiate cuisse"})
	ProselyteLg          = SetName([]string{"Proselyte sallet", "Proselyte hauberk", "Proselyte cuisse"})
	ProselyteSk          = SetName([]string{"Proselyte sallet", "Proselyte hauberk", "Proselyte tasset"})
	Granite              = SetName([]string{"Granite helm", "Granite body", "Granite legs", "Granite gloves", "Granite boots", "Granite shield", "Granite ring"})

	// Dragonhide
	GreenDHide     = SetName([]string{"Green d'hide body", "Green d'hide chaps", "Green d'hide vambraces"})
	GildedDHide    = SetName([]string{"Gilded d'hide body", "Gilded d'hide chaps", "Gilded d'hide vambraces"})
	BlueDHide      = SetName([]string{"Blue d'hide body", "Blue d'hide chaps", "Blue d'hide vambraces"})
	RedDHide       = SetName([]string{"Red d'hide body", "Red d'hide chaps", "Red d'hide vambraces"})
	BlackDHide     = SetName([]string{"Black d'hide body", "Black d'hide chaps", "Black d'hide vambraces"})
	GuthixDHide    = SetName([]string{"Guthix coif", "Guthix d'hide body", "Guthix chaps", "Guthix bracers"})
	SaradominDHide = SetName([]string{"Saradomin coif", "Saradomin d'hide body", "Saradomin chaps", "Saradomin bracers"})
	ZamorakDHide   = SetName([]string{"Zamorak coif", "Zamorak d'hide body", "Zamorak chaps", "Zamorak bracers"})
	AncientDHide   = SetName([]string{"Ancient coif", "Ancient d'hide body", "Ancient chaps", "Ancient bracers"})
	ArmadylDHide   = SetName([]string{"Armadyl coif", "Armadyl d'hide body", "Armadyl chaps", "Armadyl bracers"})
	BandosDHide    = SetName([]string{"Bandos coif", "Bandos d'hide body", "Bandos chaps", "Bandos bracers"})

	// Barrows
	Ahrims  = SetName([]string{"Ahrim's hood (Undamaged)", "Ahrim's robetop (Undamaged)", "Ahrim's robeskirt (Undamaged)", "Ahrim's staff (Undamaged)"})
	Dharoks = SetName([]string{"Dharok's helm (Undamaged)", "Dharok's platebody (Undamaged)", "Dharok's platelegs (Undamaged)", "Dharok's greataxe (Undamaged)"})
	Guthans = SetName([]string{"Guthan's helm (Undamaged)", "Guthan's platebody (Undamaged)", "Guthan's chainskirt (Undamaged)", "Guthan's warspear (Undamaged)"})
	Karils  = SetName([]string{"Karil's coif (Undamaged)", "Karil's leathertop (Undamaged)", "Karil's leatherskirt (Undamaged)", "Karil's crossbow (Undamaged)"})
	Torags  = SetName([]string{"Torag's helm (Undamaged)", "Torag's platebody(Undamaged)", "Torag's platelegs (Undamaged)", "Torag's hammers (Undamaged)"})
	Veracs  = SetName([]string{"Verac's helm (Undamaged)", "Verac's brassard (Undamaged)", "Verac's plateskirt (Undamaged)", "Verac's flail (Undamaged)"})

	// Mystic
	MysticBlue  = SetName([]string{"Mystic hat", "Mystic robe top", "Mystic robe bottom", "Mystic gloves", "Mystic boots"})
	MysticLight = SetName([]string{"Mystic hat (light)", "Mystic robe top (light)", "Mystic robe bottom (light)", "Mystic gloves (light)", "Mystic boots (light)"})
	MysticDark  = SetName([]string{"Mystic hat (dark)", "Mystic robe top (dark)", "Mystic robe bottom (dark)", "Mystic gloves (dark)", "Mystic boots (dark)"})
	MysticDusk  = SetName([]string{"Mystic hat (dusk)", "Mystic robe top (dusk)", "Mystic robe bottom (dusk)", "Mystic gloves (dusk)", "Mystic boots (dusk)"})

	// Other
	AncestralRobes       = SetName([]string{"Ancestral hat", "Ancestral robe top", "Ancestral robe bottom"})
	Bandos               = SetName([]string{"Bandos chestplate", "Bandos tassets", "Bandos boots"})
	Inquisitors          = SetName([]string{"Inquisitor's great helm", "Inquisitor's hauberk", "Inquisitor's plateskirt"})
	DagonHai             = SetName([]string{`Dagon'hai hat`, `Dagon'hai robe top`, `Dagon'hai robe bottom`})
	Justiciar            = SetName([]string{"Justiciar facedguard", "Justiciar chestguard", "Justiciar legguards"})
	ThirdAgeArmor        = SetName([]string{"3rd age full helmet", "3rd age platebody", "3rd age platelegs", "3rd age kiteshield", "3rd age longsword"})
	ThirdAgeMageRobes    = SetName([]string{"3rd age mage hat", "3rd age robe top", "3rd age robe", "3rd age amulet", "3rd age wand"})
	ThirdAgeRangeKit     = SetName([]string{"3rd age range coif", "3rd age range top", "3rd age range legs", "3rd age vambraces", "3rd age bow"})
	ThirdAgeDruidicRobes = SetName([]string{"3rd age druidic robe top", "3rd age druidic robe bottoms", "3rd age druidic cloack", "3rd age druidic staff"})
	Obsidian             = SetName([]string{"Obsidian helmet", "Obsidian platebody", "Obsidian platelegs"})
	Dragonstone          = SetName([]string{"Dragonstone full helm", "Dragonstone platebody", "Dragonstone platelegs", "Dragonstone gauntlets", "Dragonstone boots"})
	CombatPotions        = SetName([]string{"Attack potion (4 dose)", "Strength potion (4 dose)", "Defence potion (4 dose"})
	SuperCombatPotions   = SetName([]string{"Super attack (4 dose)", "Super strength (4 dose)", "Super defence (4 dose"})
	PartyHats            = SetName([]string{"Red partyhat", "Yellow partyhat", "Green partyhat", "Blue partyhat", "Purple partyhat", "White partyhat"})
	HalloweenMAsks       = SetName([]string{"Red halloween mask", "Green halloween mask", "Blue halloween mask"})
)
